### ISSUE TITLE
Assignment 1: Ready for review

### ISSUE THREAD

**Issue by sushmatn** [sushmatn/PopularPhotos#1]
My Popular Photos app with the suggested extensions is ready for review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
Excellent work, Sushma. A few notes after checking out the code:
- Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
- Good polished UI and correct use of Styles, Colors and String resources
- Great to see you were able to get the full screen Video playback working
- Great to see so many extras like photos based on place, user or hashtag.
- Great to see the like animation.
- Nice to see you used the SwipeRefreshLayout for easy stream refreshes
- Consider better organizing your source files
- Good job using the ViewHolder pattern to improve performance of photos ListView.
- Good job notifying the user on network failure.

We have provided a detailed Project 1 Feedback Guide here which covers the most common points we see for this project. Read through the feedback guide point-by-point to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this first project has given you a better sense of working with RelativeLayout which is a very flexible layout system, probably one of the most powerful responsive-first layout systems available across web and mobile platforms. This assignment also gave us our first introduction to networking, working with APIs and loading remote images. The next assignment will introduce new concept such as accepting user input and navigating between activities but will also reinforce important concepts such as networking, using APIs, handling remote images.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or or email us support@codepath.com.

P.S. Good to see you properly added the readme with features and screenshots to your project as described in the submitting assignments guide!
